# Generated by Django 5.0.4 on 2024-04-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20240425_0552'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='store_custo_first_n_8f83e0_idx',
            old_name='store_custo_first_n_a7e990_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
