# Generated by Django 5.0.4 on 2024-04-25 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_store_custo_first_n_a7e990_idx_store_custo_first_n_8f83e0_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
