# Generated by Django 5.1.4 on 2025-01-05 07:14

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_remove_customer_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="placed_at",
            new_name="Order_placed_at",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="Collection",
            new_name="collection",
        ),
        migrations.RemoveField(
            model_name="product",
            name="unit_price",
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(default="9807860786", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default="0.00", max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="title", unique=True
            ),
        ),
    ]
