# Generated by Django 5.1.4 on 2025-01-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_rename_placed_at_order_order_placed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(max_length=20),
        ),
    ]
