# Generated by Django 5.1.4 on 2025-01-07 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_product_slug"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OderItem",
            new_name="OrderItem",
        ),
    ]
