# Generated by Django 5.1.4 on 2025-01-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_rename_oderitem_orderitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["title"]},
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(),
        ),
    ]
