# Generated by Django 5.0.4 on 2025-01-26 10:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_alter_customer_options_alter_product_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=True),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: [
                setattr(cart, 'uuid', uuid.uuid4()) or cart.save()
                for cart in apps.get_model('store', 'Cart').objects.filter(uuid__isnull=True)
            ],
            reverse_code=migrations.RunPython.noop,
        ),
        # Skipped altering 'id' field to UUID in production. Handled manually or ignored.
    ]