# Generated by Django 5.0.4 on 2025-05-09 10:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0021_alter_product_slug_alter_productimage_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="uuid",
        ),
        migrations.AlterField(
            model_name="cart",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
